---
command: C:\Users\patro\Downloads\leela-zero-0.10-source\msvc\x64\Release\leelaz.exe -d -t 1 -p 1600 --noponder -w C:\Users\patro\Downloads\leela-zero-0.10-source\msvc\x64\Release\leelaz-model-3008000.txt
tests:
  # Ladder tests
  - sgf: ladder1.sgf
    group: ladder
    move: black
    no_move:
      - P7
  - sgf: ladder2.sgf
    group: ladder
    move: black
    no_move:
      - G4
  - sgf: ladder3.sgf
    group: ladder
    move: white
    no_move:
      - P11
  - sgf: ladder4.sgf
    group: ladder
    move: black
    no_move:
      - P6
  - sgf: ladder5.sgf
    group: ladder
    move: white
    no_move:
      - J6
  - sgf: ladder6.sgf
    group: ladder
    move: white
    no_move:
      - F14
  - sgf: ladder7.sgf
    group: ladder
    move: white
    no_move:
      - G6

  # Life & Death tests
  - sgf: lifedeath1.sgf
    group: lifedeath
    move: white
    yes_move:
      - M10
  - sgf: lifedeath2.sgf
    group: lifedeath
    number: 220
    move: white
    yes_move:
      - S19 # Secure top right corner
  - sgf: longdragon1.sgf
    group: lifedeath
    move: white
    max_win_rate: 40
  - sgf: longdragon2.sgf
    group: lifedeath
    move: white
    max_win_rate: 40
  - sgf: winrate_easy1.sgf
    group: lifedeath
    move: white
    max_win_rate: 40

  # Large group sensitive tests
  - sgf: largegroup1.sgf
    group: largegroup
    number: 294
    move: white
    yes_move:
      - E1

  - sgf: endgame1.sgf
    group: endgame
    number: 289
    move: black
    yes_move:
      - S19

  - sgf: endgame2.sgf
    group: endgame
    number: 270
    move: white
    no_move:
      - G19
